// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("CircuitBreaker.Net")]
[assembly: AssemblyDescriptionAttribute("Implementation of CircuitBreaker pattern on .NET")]
[assembly: AssemblyCopyrightAttribute("Copyright 2015")]
[assembly: GuidAttribute("dc40055a-b114-422e-b9bf-555fe23d9305")]
[assembly: AssemblyProductAttribute("CircuitBreaker.Net")]
[assembly: AssemblyVersionAttribute("0.2.3.0")]
[assembly: AssemblyFileVersionAttribute("0.2.3.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.3.0";
    }
}
